{
 "title": "IoT Sensor Application",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2023-01-06T00:00:00.000Z" },
 "panels": [
  {
   "title": "Average TH2 per Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "parsedQuery": "Temp.Aggregated_TH2.find({})", "query": "Temp.Aggregated_TH2.find({})" }
   ]
  },
  {
   "title": "Raw TH1 Chart",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "parsedQuery": "Raw.Temp.find({\"Sensor\":\"TH1\"})",
     "query": "Raw.Temp.find({Sensor: \"TH1\"})"
    }
   ]
  },
  {
   "title": "Late Rejected Evenets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "parsedQuery": "Water.Late_Events_Rejected.find({})",
     "query": "Water.Late_Events_Rejected.find({})"
    }
   ]
  },
  {
   "title": "Raw W1 Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "parsedQuery": "Raw.Water.find({\"Sensor\":\"W1\"})",
     "query": "Raw.Water.find({Sensor: \"W1\"})"
    }
   ]
  },
  {
   "title": "Etot Daily Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "parsedQuery": "Energy.Aggregated_Etot.find({})",
     "query": "Energy.Aggregated_Etot.find({})"
    }
   ]
  },
  {
   "title": "Water Leakage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "parsedQuery": "Water.Leak.find({})", "query": "Water.Leak.find({})" }
   ]
  }
 ]
}